name: Update repo to match @matterlabs/zksync-contracts

on:
  push:
  schedule:
    # Everyday at 3AM
    - cron: '0 3 * * *'
jobs:
  check-update-version-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check npm version
        run: yarn outdated
        continue-on-error: true
        id: check_outdated
      - name: Get Updated Version
        if: steps.check_outdated.outcome != 'success'
        id: get_updated
        run: |
          yarn upgrade --latest
          cp -r node_modules/@matterlabs/zksync-contracts/* zksync-contracts/
          jq '.dependencies."@matterlabs/zksync-contracts"' package.json | sed 's/"//g' | sed 's/\^//g' > version.txt
          version=$(cat version.txt)
          echo "::set-output name=version::${version}"
      - name: add and commit
        if: steps.check_outdated.outcome != 'success'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          tagging_message: ${{steps.get_updated.outputs.version}}
          commit_message: ${{steps.get_updated.outputs.version}}
      - name: Create Release
        if: steps.check_outdated.outcome != 'success'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{steps.get_updated.outputs.version}}
          release_name: ${{steps.get_updated.outputs.version}}
          draft: false
          prerelease: false